djangoProject2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('submission.urls')),  # Includes URLs from the 'submission' app
    # ... you can include URLs from other apps here if needed ...
]

submission/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.index, name='index'),  # Homepage at the root URL
    path('login/', auth_views.LoginView.as_view(template_name='submission/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('submit/', views.submit_text, name='submit_text'),  # URL for submitting text
    path('submission/<int:pk>/', views.submission_detail, name='submission_detail'),
    path('submission/<int:pk>/delete/', views.delete_submission, name='delete_submission'),
    # ... you can add more URL patterns here if needed ...
]

textanalyzer/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('submission.urls')),  # Includes URLs from the 'submission' app
    # ... you can include URLs from other apps here if needed ...
]

submission/models.py
from django.db import models
from django.utils import timezone
from django.db.models import JSONField


class TextSubmission(models.Model):
    title = models.CharField(max_length=200)
    submission_text = models.TextField()
    word_count = models.IntegerField(default=0)
    submission_time = models.DateTimeField(default=timezone.now)

    readability_scores = JSONField(default=dict)


    # Fields for readability scores
    # flesch_reading_ease = models.FloatField(null=True, blank=True)
    # flesch_reading_ease = models.FloatField(null=True, blank=True)
    # smog_index = models.FloatField(null=True, blank=True)
    # flesch_kincaid_grade = models.FloatField(null=True, blank=True)
    # coleman_liau_index = models.FloatField(null=True, blank=True)
    # automated_readability_index = models.FloatField(null=True, blank=True)
    # dale_chall_readability_score = models.FloatField(null=True, blank=True)
    # difficult_words = models.IntegerField(null=True, blank=True)
    # linsear_write_formula = models.FloatField(null=True, blank=True)
    # gunning_fog = models.FloatField(null=True, blank=True)
    # text_standard = models.CharField(max_length=100, null=True, blank=True)


class ReadabilityTestInfo(models.Model):
    test_name = models.CharField(max_length=100)  # This is the field name in your TextSubmission model
    display_name = models.CharField(max_length=100)  # A human-readable name for display purposes
    description = models.TextField()
    more_info_link = models.URLField()

    def __str__(self):
        return self.test_name

submission/forms.py
from django import forms


class TextSubmissionForm(forms.Form):
    title = forms.CharField(max_length=200)
    submission_text = forms.CharField(widget=forms.Textarea)

submission/views.py
from django.shortcuts import render, redirect
from .forms import TextSubmissionForm
from .models import TextSubmission, ReadabilityTestInfo
import textstat
from django.db.models import Avg, Count
from django.shortcuts import get_object_or_404
from .tasks import fetch_openai_scores  # Assuming you have this task set up for Celery
from django.contrib.auth.decorators import login_required


@login_required
def submission_detail(request, pk):
    submission = get_object_or_404(TextSubmission, pk=pk)
    testinfos = ReadabilityTestInfo.objects.all()
    return render(request, 'submission/submission_detail.html', {
        'submission': submission, 'testinfos': testinfos,
    })


@login_required
def delete_submission(request, pk):
    submission = get_object_or_404(TextSubmission, pk=pk)
    if request.method == 'POST':
        submission.delete()
        return redirect('index')  # Assuming 'index' is the name of your URL pattern for the submission list page.
    else:
        # Redirect to detail view if not a POST request, as a fallback.
        return redirect('submission_detail', pk=pk)


@login_required
def submit_text(request):
    if request.method == 'POST':
        form = TextSubmissionForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            submission_text = form.cleaned_data['submission_text']
            word_count = len(submission_text.split())

            # Create TextSubmission instance
            submission = TextSubmission(title=title, submission_text=submission_text, word_count=word_count)

            # Calculate readability scores
            submission.readability_scores['smog_index'] = [{
                'score': textstat.smog_index(submission_text),
                'source': 'textstat'
            }]
            submission.readability_scores['flesch_kincaid_grade'] = [{
                'score': textstat.flesch_kincaid_grade(submission_text),
                'source': 'textstat'
            }]
            submission.readability_scores['coleman_liau_index'] = [{
                'score': textstat.coleman_liau_index(submission_text),
                'source': 'textstat'
            }]
            submission.readability_scores['gunning_fog'] = [{
                'score': textstat.gunning_fog(submission_text),
                'source': 'textstat'
            }]

            submission.save()

            # Asynchronously fetch scores from OpenAI (Celery task)
            fetch_openai_scores.delay(submission.id, submission.submission_text)

            # Redirect or show success message
            redirect('/submission/{}'.format(submission.id))

    else:
        form = TextSubmissionForm()

    return render(request, 'submission/submit_text.html', {'form': form})


@login_required
def index(request):
    submissions = TextSubmission.objects.all()
    return render(request, 'submission/index.html', {'submissions': submissions})

submission/templates/submission/base.html
{%  load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}TextAnalyzer{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'submission/css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">TextAnalyzer</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'submit_text' %}">Submit Text</a>
                    </li>
                </ul>
                {% if user.is_authenticated %}
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                </ul>
                {% endif %}
                    <!-- Add more navbar items here -->
            </div>
        </div>
    </nav>

    <!-- Main Content -->
    <div class="container mt-4">
        {% block content %}
        <!-- Content goes here -->
        {% endblock %}
    </div>

    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <script>
        document.getElementById('loginForm').addEventListener('submit', function() {
        document.getElementById('spinner').style.display = 'block'; // Show the spinner
        // Optionally, disable the submit button to prevent multiple submissions
        this.querySelector('[type="submit"]').disabled = true;});
    </script>
</body>
</html>

submission/templates/submission/index.html
{% extends 'submission/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <div class="container mt-4">
        <h1>Welcome to Our Text Analysis Site</h1>
        <p>This is the homepage where you can see a list of text submissions.</p>

        <!-- Table of submissions -->
        <table class="table table-hover mt-3">
            <thead class="table-light">
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Title</th>
                    <th scope="col">Date Submitted</th>
                </tr>
            </thead>
            <tbody>
                {% for submission in submissions %}
                <tr onclick="location.href='{% url 'submission_detail' submission.id %}'" style="cursor: pointer;">
                    <th scope="row">{{ submission.id }}</th>
                    <td>{{ submission.title }}</td>
                    <td>{{ submission.submission_time }}</td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="3">No submissions available.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

submission/templates/submission/login.html
{% extends 'submission/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card mt-5">
                    <div class="card-body">
                        <h2 class="card-title text-center mb-4">Login</h2>
                        <form action="{% url 'login' %}" method="post">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="username" class="form-label">Username</label>
                                <input type="text" class="form-control" id="username" name="username" required>
                            </div>
                            <div class="mb-3">
                                <label for="password" class="form-label">Password</label>
                                <input type="password" class="form-control" id="password" name="password" required>
                            </div>
                            <div class="d-grid gap-2">
                                <button type="submit" class="btn btn-primary">Login</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

submission/templates/submission/submission_detail.html
{% extends 'submission/base.html' %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-3">Submission Detail: {{ submission.title }}</h2>
    <p><strong>Submitted on:</strong> {{ submission.submission_time }}</p>

    <div class="accordion" id="accordionText">
        <div class="accordion-item">
            <h2 class="accordion-header">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapsesub{{ submission.id }}" aria-expanded="true" aria-controls="collapsesub{{  submission.id }}">
                Text Submitted
              </button>
            </h2>
            <div id="collapsesub{{ submission.id }}" class="accordion-collapse collapse" data-bs-parent="#accordionText">
              <div class="accordion-body">
                {{ submission.submission_text }}
              </div>
            </div>
        </div>
    </div>

    <!-- Readability Scores Section -->
    <div class="container mt-3">
        <h2 class="mb-3">Readability Scores</h2>
    </div>
    
    <div class="container text-left">
        {% for key, value in submission.readability_scores.items %}
            <div class="row align-items-start">
                <div class="col">
                  <strong>{{ key|title }}:</strong>
                </div>
                {% for item in value %}
                    <div class="col">
                        {{ item.score }}
                        <span class="badge bg-secondary">{{ item.source }}</span>
                    </div>
                {% endfor %}
              </div>
        {% endfor %}
    </div>

    <br>
    <br>
    <!-- Readability TestInfo Section -->
    <div class="container mt-3">
        <h2 class="mb-3">Test Information</h2>
    </div>

    <div class="accordion" id="accordionTextExplain">
        {% for testinfo in testinfos %}
        <div class="accordion-item">
            <h2 class="accordion-header">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapsetest{{ testinfo.id }}" aria-expanded="true" aria-controls="collapsetest{{ testinfo.id }}">
                {{ testinfo.display_name }}
              </button>
            </h2>
            <div id="collapsetest{{ testinfo.id }}" class="accordion-collapse collapse" data-bs-parent="#accordionTextExplain">
              <div class="accordion-body">
                  <p>{{ testinfo.description }}</p>
                  <a href={{ testinfo.more_info_link }}>More Info </a>
              </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <div class="container mt-3">
        <form action="{% url 'delete_submission' submission.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this submission?');">Delete</button>
        </form>
    </div>

</div>
{% endblock %}

submission/templates/submission/submit_text.html
{% extends 'submission/base.html' %}
{%  load static %}

{% block title %}Submit Text{% endblock %}

{% block content %}
    <h2 class="mb-4">Submit Your Text</h2>
    <form method="post" class="row g-3">
        {% csrf_token %}
        <div class="col-md-6">
            <label for="id_title" class="form-label">Title</label>
            <input type="text" class="form-control" id="id_title" name="title" required>
        </div>
        <div class="col-md-12">
            <label for="id_submission_text" class="form-label">Text</label>
            <textarea class="form-control" id="id_submission_text" name="submission_text" rows="5" required></textarea>
        </div>
        <div class="col-12">
            <button type="submit" class="btn btn-primary">Submit</button>
            <div id="spinner" class="spinner" style="display: none;"></div>
        </div>
    </form>
{% endblock %}